print("syntax error means there is a problem in the grammar of the expression")
print("." * 5)
print("An IDE is a code editor with features for autocompletion and debugging.")
print("." * 10)
print("File extensions for a python app is .py")
print("." * 15)
print("A linter is to check for syntax errors.")
print("." * 20)
print("PEP8 is a style guide for best practices in python")
print("." * 30)
print("machine code is specific to a type of operating system/CPU")
print("." * 30)
print ("order of execution: Python language, cpython, bytecode, virtual machine, machine code")
print("." * 30)